# Config for A SkyBlock (also playable as AcidIsland)
general:
   # Sea level height (don't changes this mid-game unless you delete the world)
   # Minimum is 0, which means you are playing sky block!
   # If sea level is less than about 10, then players will drop right through it
   # if it exists. Makes for an interesting variation on sky block.
   sealevel: 0

   # Island level - the height of the island.
   # Height should not be lower than sea level, but can be if you have an
   # island schematic that supports it
   # Lowest level is 5
   islandlevel: 120

   # Name of the world - if it does not exist then it will be generated
   worldName: ASkyBlock

   # Use the control panel as the default display for /island
   # /island will always create an island if one does not exist
   # If the control panel is not used, then /island will teleport the player home
   usecontrolpanel: false

   # Create Nether - if this is false, the nether world will not be made and access to
   # AcidIsland control of the nether will not occur. Other plugins may still enable
   # portal usage.
   # Note: Some challenges will not be possible if there is no nether.
   # Note that in AcidIsland, all players arrive at the same portal and entering a
   # portal will return them back to their islands.
   createnether: true

   #How long a player must wait before they can reset their island again
   resetwait: 300

   #How many resets a player is allowed (override with /asadmin clearreset <player>
   #Value of -1 means unlimited, 0 means hardcore - no resets.
   #Example, 2 resets means they get 2 resets or 3 islands lifetime
   resetlimit: 2

   # Ops receive damage from acid (Set to true if you want Ops to play properly)
   damageops: false

   # Acid damage to player per second by being in acid if they have no armor on.
   # A fully health player has 20 health points. Players will regen some health
   # so the default will give players about 3 seconds to get out the acid
   # 0 = no damage, 10 = default damage, 20 = instant death
   aciddamage: 0
   # Damage that monsters will experience.
   mobaciddamage: 0
   # Damage that rain does.
   raindamage: 0

   # Damage type to apply in addition to acid damage
   # Types can be : SLOW, SLOW_DIGGING, CONFUSION,BLINDNESS, HUNGER, WEAKNESS and POISON
   # If you just want these to act, then make the acid damage 0 above
   # Note - these are potion effects and so can be cured by milk
   damagetype:

   # Removing mobs - this kills all monsters in the vicinity. Benefit is that it helps
   # players return to their island if the island has been overrun by monsters
   # Con is that it kills any mob grinders 
   # Remove mobs when logging in
   loginremovemobs: true

   # Remove mobs when /island
   islandremovemobs: false

   # Sets the limit for number of monsters that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   monsterspawnlimit: 70

   #[integer] Sets the limit for number of animals that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   animalspawnlimit: 15

   #[integer] Sets the limit for number of water animals [squid] that can spawn in a chunk in this world. 
   # Note: If set to a negative number the world will use the server-wide spawn limit instead.
   # Max is 100
   wateranimalspawnlimit: 15

   #[integer] Island below this level will be removed if they are abandoned and admins issue the purge command
   abandonedislandlevel: 10

   # Reset Money - if this is true, will reset the player's money to
   # the starting money (see below) when they start an island or reset
   resetmoney: true

   # Starting money - this is how much money new players will have as their balance at the start of an island. (Default is zero)
   startingmoney: 10.00

   # Reset Challenges - if this is true, player's challenges will reset when they
   # reset an island
   resetchallenges: true

   # Reset inventory - if true, the player's inventory will be cleared when they start
   # or restart and island. Default is true.
   # Note: if you have MultiInv running or a similar inventory control plugin, that
   # plugin may still reset the inventory when the world changes.
   resetinventory: true

   # Nether spawn protection radius - this is the distance around the nether spawn point that will be protected from player interaction (breaking blocks, pouring lava etc.). Minimum is 0 (not recommended), maximum is 100. Default is 25.
   netherspawnradius: 25

   # Broadcast 1st time challenge completion messages to all players
   broadcastmessages: true

   # Allow /island teleport when falling. If set to false, all teleporting is
   # disabled until death from the void...
   allowfallingteleport: true

island:
   # Space between islands in blocks
   distance: 110

   # The size of the protective region for each island. Must be less than distance
   protectionRange: 100

   # Coordinate offset - never change this mid-game and there is no
   # need to set this. It is for compatibility with IslandWorld maps and set by
   # BlockConverter.
   xoffset: 0
   zoffset: 0

   # Max team size
   maxteamsize: 4
   # VIP team size - set by permission askyblock.team.vip
   vipteamsize: 8
   # VIP2 team size - set by permission askyblock.team.vip2
   vip2teamsize: 12

   # Items that will be in the chest when the player starts an island
   # Must be in Bukkit Materials format. Format is <Material>:<Qty>
   # or <Material>:<Damage>:<Qty>
   # Use <Damage> to set the durability of a item or to select sub-items/colors.
   # Format for POTION is POTION:<effect>:<qty> or POTION:<effect>:<type>:<qty>
   # <type> is EXTENDED, SPLASH or EXTENDEDSPLASH. Not all potions can be extended.
   # Check console for errors and guidance after typing /acid reload
   chestItems: 'ICE:2 MELON:1 TORCH:2 BONE:1 LAVA_BUCKET:1 PUMPKIN_SEEDS:1 SUGAR_CANE:1 RED_MUSHROOM:1 BROWN_MUSHROOM:1 CACTUS:1 BREAD:1 WHEAT:1 LEATHER_BOOTS:1 LEATHER_HELMET:1 LEATHER_CHESTPLATE:1 LEATHER_LEGGINGS:1'
   # Island Protection Settings
   #PVP is allowed or denied. (Values = allow or deny)
   allowPvP: deny
   # Other players can break blocks or not or generally damage things
   allowbreakblocks: false
   # Other players can place blocks
   allowplaceblocks: false
   # Allow players to be able to sleep in beds not on their island
   allowbeduse: false
   # Allow players to use buckets, either fill or dump them
   allowbucketuse: false
   # Allow players to shear sheep
   allowshearing: false
   # Allow players to throw enderpearls and teleport
   allowenderpearls: false
   # Allow players to use doors or trapdoors. If a door is operated by a button or redstone, this does not count
   allowdooruse: false
   # Allow players to use levers or buttons
   allowleverbuttonuse: false
   # Allow players to trample crops
   allowcroptrample: false
   # Allow players to access chests of any kind, droppers, dispensers and hoppers
   allowchestaccess: false
   # Allow players to access furnaces
   allowfurnaceuse: false
   # Allow players to adjust diodes or comparators
   allowredstone: false
   # Allow players to use jukeboxes, eject discs and hit note blocks
   allowmusic: false
   # Allow players to use crafting benches
   allowcrafting: true
   # Allow players to use cauldrons and brewing stands
   allowbrewing: false
   # Allow gates to be used
   allowgateuse: false
   # Allow friendly mobs to be hurt (cows etc.)
   allowhurtmobs: true
   # Allow Enderman Griefing (default is to allow, see next setting)
   allowendermangriefing: true
   # Make enderman drop the block he is holding if he dies (recommended)
   endermandeathdrop: true
   # Allow creeper explosion damage to block (explosion still hurts)
   allowcreeperdamage: true
   # Allow TNT damage to blocks (stops players using TNT to destroy other's islands)
   allowtntdamage: false

# This section contains the biomes that can be bought or used
biomesettings:
  # The default cost for changing biome. Can be over-ridden by the Biome settings
  # Default is 100 if this is not set. Cannot be <0.
  defaultcost: 100

# List of biomes and their settings.
# Cost - cost in currency to change to that biome
# permission - the permission required to use that biome
# If the biome is not listed, it is not available
biomes:
  COLD_TAIGA:
    icon: SAPLING
    description: Snow and wolves.
    plants:
      LONG_GRASS: 10:GRASS:1
    mobs:
      WOLF: 5:SNOW
  DESERT:
    icon: DEAD_BUSH
    description: Dry, water evaporates, no ice or snow. Cactus and other desert plants spawn.
    confirm: true
    removewater: true
    removeice: true
    removesnow: true
    plants:
      DEAD_BUSH: 10:SAND
      CACTUS: 10:SAND
    conversions: DIRT:0:30:SAND:0
  FLOWER_FOREST:
    icon: RED_ROSE
    description: The place for flowers!
    plants:
      RED_ROSE: 2:GRASS:8
      DOUBLE_PLANT: 4:GRASS:5
      LONG_GRASS: 20:GRASS:1
  HELL:
    icon: STATIONARY_LAVA
    confirm: true
    cost: 1000
    permission: askyblock.biomes.hell
    friendlyname: Nether
    description: All water, snow and ice will be removed in this unusual biome.
    removewater: true
    removeice: true
    removesnow: true
    mobs:
      PIG_ZOMBIE: 10:NETHERRACK
  JUNGLE:
    icon: VINE
    description: Lush environment, fun plants spawn. No ice or snow.
    removeice: true
    removesnow: true
    plants:
      YELLOW_FLOWER: 20:GRASS
      MELON_BLOCK: 10:GRASS
      RED_ROSE: 20:GRASS
      DOUBLE_PLANT: 20:GRASS:3
      LONG_GRASS: 20:GRASS:2
  MUSHROOM_ISLAND:
    icon: RED_MUSHROOM
    permission: askyblock.biomes.mushoom_island
    description: Mushroom island
    plants:
      BROWN_MUSHROOM: 10:MYCEL
      RED_MUSHROOM: 10:MYCEL
    mobs:
      MUSHROOM_COW: 10:MYCEL
  OCEAN:
    icon: STATIONARY_WATER
    description: Where squids may spawn.
    cost: 500
    mobs:
      SQUID: 10:STATIONARY_WATER
  PLAINS:
    icon: GRASS
    description: Wild horses may roam here.
    cost: 0
    plants:
      LONG_GRASS: 10:GRASS:1
    mobs:
      HORSE: 10:GRASS
  SUNFLOWER_PLAINS:
    icon: DOUBLE_PLANT
    description: Home of the sunflower!
    plants:
      DOUBLE_PLANT: 20:GRASS:0
      LONG_GRASS: 20:GRASS:1
  SWAMPLAND:
    icon: WATER_LILY
    description: When the moon is full, you-know-what may spawn...
    plants:
      RED_MUSHROOM: 20:GRASS
      BROWN_MUSHROOM: 20:GRASS
      WATER_LILY: 5:STATIONARY_WATER
    mobs:
      SLIME: 5:STATIONARY_WATER